version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-graphrag
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - graphrag-network

  app:
    build: .
    container_name: streamlit-graphrag
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "80:80"
    depends_on:
      - neo4j
    networks:
      - graphrag-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  graphrag-network:
    driver: bridge 